version: '2'
services:
  db:
    image: neo4j
    environment:
      NEO4J_AUTH: neo4j/admin
    volumes:
      - ./neo_data:/data
    cap_add:
      - SYS_RESOURCE
  web:
    container_name: web
    ports:
      - "3000:3000"
      # - "35729:35729"
    build:
      context: .
      dockerfile: ./dockerfiles/node/Dockerfile
    # command: bash -c "cd /usr/src/app && npm install && node ./node_modules/webpack/bin/webpack.js && node app/index.js"
    links:
      - db
    # command: tail -f /dev/null
    command: bash -c "while ! curl -s db:7474; do echo neo4j service not available, sleeping...; sleep 3; done; node app/index.js"
    volumes:
      - ./:/usr/src/app